---
apiVersion: v1
kind: Service
metadata:
  name: cloud-cost-backend
  namespace: cloud-cost
  labels:
    app.kubernetes.io/name: cloud-cost-dashboard
    app.kubernetes.io/component: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      name: http
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: cloud-cost-frontend
  namespace: cloud-cost
  labels:
    app.kubernetes.io/name: cloud-cost-dashboard
    app.kubernetes.io/component: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
  type: ClusterIP
